name = "docbuild"
version = "0.1.0"
packagesDir = "../.lake/packages"
reservoir = false

[[require]]
name = "doc-gen4"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
scope = "leanprover"

[[require]]
name = "AInfinity"
path = "../"
