module

public import Mathlib

@[expose] public section

open CategoryTheory

namespace AInfinityCategoryTheory

universe v u
variable {R : Type u} [CommRing R] [DecidableEq R] (C : Type u) [Category C]
variable {n : ℕ}

structure KLRWCategory (n : ℕ) (R : Type u) where
  positioning : Fin (n + 1)

/--
The free module generated by the strands with fixed channels.
This is an abbrev because we want it to inherit the Module typeclass instance from DFinsupp.

Uses DFinsupp because Finsupp is not currently computable. See
https://leanprover.zulipchat.com/#narrow/channel/113489-new-members/topic/Finsupp.20noncomputability
-/
abbrev StrandSpace (R : Type u) [CommRing R] : Type u := Π₀ _ : ℕ, R

abbrev StrandSpace.dots (R : Type u) [CommRing R] (n : ℕ) : StrandSpace R :=
  DFinsupp.single n 1

section ConvolutionLemmas
variable {R : Type u} [CommRing R] [DecidableEq R]

private theorem sum_inner_zero (h : StrandSpace R) (k : ℕ) :
    h.sum (fun l u => ((0 : R) * u) • StrandSpace.dots R (k + l + 0)) = 0 := by
  simp [zero_mul, zero_smul]

private theorem sum_inner_add (h : StrandSpace R) (k : ℕ) (a b : R) :
    h.sum (fun l u => ((a + b) * u) • StrandSpace.dots R (k + l + 0)) =
    h.sum (fun l u => (a * u) • StrandSpace.dots R (k + l + 0)) +
    h.sum (fun l u => (b * u) • StrandSpace.dots R (k + l + 0)) := by
  simp only [add_mul, add_smul, DFinsupp.sum, Finset.sum_add_distrib]

private theorem smul_dots_sum_single_index {R : Type u} [CommRing R] [DecidableEq R]
    (c : R) (m : ℕ) (g : ℕ → R → StrandSpace R) (hg : g m 0 = 0) :
    (c • StrandSpace.dots R m).sum g = g m c := by
  rw [StrandSpace.dots, ← DFinsupp.single_smul, smul_eq_mul, mul_one,
      DFinsupp.sum_single_index hg]

private theorem smul_dots_sum_lhs {R : Type u} [CommRing R] [DecidableEq R]
    (c : R) (m : ℕ) (h : StrandSpace R) :
    (c • StrandSpace.dots R m).sum
      (fun k t => h.sum (fun l u => (t * u) • StrandSpace.dots R (k + l + 0))) =
    h.sum (fun l u => (c * u) • StrandSpace.dots R (m + l + 0)) := by
  rw [StrandSpace.dots, ← DFinsupp.single_smul, smul_eq_mul, mul_one,
      DFinsupp.sum_single_index (by simp [zero_mul, zero_smul])]

private theorem smul_dots_sum_rhs {R : Type u} [CommRing R] [DecidableEq R]
    (c : R) (m : ℕ) (r : R) (i : ℕ) :
    (c • StrandSpace.dots R m).sum
      (fun k t => (r * t) • StrandSpace.dots R (i + k + 0)) =
    (r * c) • StrandSpace.dots R (i + m + 0) := by
  rw [StrandSpace.dots, ← DFinsupp.single_smul, smul_eq_mul, mul_one,
      DFinsupp.sum_single_index (by simp [mul_zero, zero_smul])]

end ConvolutionLemmas

instance : Category (KLRWCategory n R) where
  Hom X Y := StrandSpace R
  id X := StrandSpace.dots R 0
  comp {X Y Z} g h :=
    g.sum (fun i r => h.sum (fun j s => (r * s) • StrandSpace.dots R (i + j + 0)))
    -- + 0 should theoretically be + u
    -- we want C[u, h] to ignore grading
  id_comp f := by
    simp only [StrandSpace.dots]
    rw [DFinsupp.sum_single_index (by simp [zero_mul, zero_smul])]
    simp only [one_mul, zero_add, add_zero, ← DFinsupp.single_smul, smul_eq_mul, mul_one]
    exact DFinsupp.sum_single
  comp_id f := by
    simp only [StrandSpace.dots]
    conv_lhs =>
      arg 2; ext i r
      rw [DFinsupp.sum_single_index (by simp [mul_zero, zero_smul])]
    simp [mul_one, add_zero, ← DFinsupp.single_smul, smul_eq_mul]
  assoc f g h := by
    -- Flatten LHS outer sum: pull f.sum out
    rw [DFinsupp.sum_sum_index (fun k => sum_inner_zero h k)
          (fun k a b => sum_inner_add h k a b)]
    congr 1; funext i; funext r
    -- Flatten LHS inner sum: pull g.sum out
    rw [DFinsupp.sum_sum_index (fun k => sum_inner_zero h k)
          (fun k a b => sum_inner_add h k a b)]
    -- Reduce (c • dots m).sum on LHS
    simp_rw [smul_dots_sum_lhs]
    -- LHS = g.sum(fun j s => h.sum(fun l u => ((r*s)*u) • dots((i+j+0)+l+0)))
    -- Flatten RHS: pull g.sum out
    symm
    rw [DFinsupp.sum_sum_index
          (fun k => by simp [mul_zero, zero_smul])
          (fun k a b => by simp [mul_add, add_smul])]
    congr 1; funext j; funext s
    -- Flatten RHS inner sum: pull h.sum out
    rw [DFinsupp.sum_sum_index
          (fun k => by simp [mul_zero, zero_smul])
          (fun k a b => by simp [mul_add, add_smul])]
    -- Reduce (c • dots m).sum on RHS
    simp_rw [smul_dots_sum_rhs]
    -- RHS = h.sum(fun l u => (r*(s*u)) • dots(i+(j+l+0)+0))
    symm
    -- Compare pointwise
    congr 1; funext l; funext u
    simp only [mul_assoc, add_assoc, Nat.add_zero]

instance : Preadditive (KLRWCategory n R) where
  homGroup P Q := inferInstanceAs (AddCommGroup (StrandSpace R))
  add_comp := by
    intro P Q S f f' g
    letI : AddCommMonoid (StrandSpace R) := inferInstance
    exact DFinsupp.sum_add_index (fun k => sum_inner_zero g k)
      (fun k a b => sum_inner_add g k a b)
  comp_add := by
    intro P Q S f g g'
    letI : AddCommMonoid (StrandSpace R) := inferInstance
    suffices h : (f : StrandSpace R).sum (fun i r =>
        (g + g' : StrandSpace R).sum (fun j s => (r * s) • StrandSpace.dots R (i + j + 0))) =
      (f : StrandSpace R).sum (fun i r =>
        (g : StrandSpace R).sum (fun j s => (r * s) • StrandSpace.dots R (i + j + 0))) +
      (f : StrandSpace R).sum (fun i r =>
        (g' : StrandSpace R).sum (fun j s => (r * s) • StrandSpace.dots R (i + j + 0)))
      from h
    conv_lhs =>
      arg 2; ext i r
      rw [DFinsupp.sum_add_index (fun j => by simp [mul_zero, zero_smul])
        (fun j s₁ s₂ => by simp [mul_add, add_smul])]
    simp only [DFinsupp.sum, Finset.sum_add_distrib]

abbrev AddKLRWCategory (n : ℕ) (R : Type u) [CommRing R] [DecidableEq R] : Type _ :=
  Mat_ (KLRWCategory n R)

abbrev KLRWComplexCategory (n : ℕ) (R : Type u) [CommRing R] [DecidableEq R] : Type _ :=
  CochainComplex (AddKLRWCategory n R) ℤ

end AInfinityCategoryTheory
