module

public import Mathlib
public import AInfinity.Texify
public meta import AInfinity.Texify
public import AInfinity.AdditiveCompletion
public import AInfinity.BoundedCochainComplex

@[expose] public section

open CategoryTheory

namespace AInfinityTheory

universe v u
variable {R : Type u} [CommRing R] [DecidableEq R] (C : Type u) [Category C]
variable {n : ℕ}

structure KLRWCategory (n : ℕ) (R : Type u) where
  positioning : Fin (n + 1)

instance : Texify (KLRWCategory n R) where
  texify x := s!"T_\{{x.positioning}}"
  requiresParentheses := false

def compShift {n : ℕ} {R : Type u}
    (X Y Z : KLRWCategory n R) : ℕ :=
  max X.positioning.val Y.positioning.val +
      max Y.positioning.val Z.positioning.val -
      max X.positioning.val Z.positioning.val -
      Y.positioning.val

lemma compShift_self_left {n : ℕ} {R : Type u}
    (X Y : KLRWCategory n R) :
    compShift X X Y = 0 := by
  dsimp [compShift]
  omega

lemma compShift_self_right {n : ℕ} {R : Type u}
    (X Y : KLRWCategory n R) :
    compShift X Y Y = 0 := by
  dsimp [compShift]
  omega

lemma compShift_assoc {n : ℕ} {R : Type u}
    (W X Y Z : KLRWCategory n R) :
    compShift W X Y + compShift W Y Z =
      compShift X Y Z + compShift W X Z := by
  dsimp [compShift]
  omega

/--
The free module generated by the strands with fixed channels.
This is an abbrev because we want it to inherit the Module typeclass instance from DFinsupp.

Uses DFinsupp because Finsupp is not currently computable. See
https://leanprover.zulipchat.com/#narrow/channel/113489-new-members/topic/Finsupp.20noncomputability
-/
abbrev StrandSpace (R : Type u) [CommRing R] : Type u := Π₀ _ : ℕ, R

instance [ToString R] : Texify (StrandSpace R) where
  texify x :=
    -- Not sure if this computationally efficient
    let support := x.support
    if support = ∅ then
      "0"
    else
      support.sort (· ≥ ·) |>.map (termString x) |> " + ".intercalate
  requiresParentheses := true
  where termString (x : ℕ → R) (i : ℕ) :=
    let coefficient := x i
    if i = 0 then
      toString coefficient
    else
      let coefficientString :=
        if coefficient = 1 then ""
        else if coefficient = -1 then "-"
        else toString coefficient
      let powerString := if i = 1 then "" else s!"^\{{i}}"
      s!"{coefficientString}s{powerString}"

abbrev StrandSpace.dots (R : Type u) [CommRing R] (n : ℕ) : StrandSpace R :=
  DFinsupp.single n 1

section ConvolutionLemmas
variable {R : Type u} [CommRing R] [DecidableEq R]

private theorem sum_inner_zero (h : StrandSpace R) (k t : ℕ) :
    h.sum (fun l u => ((0 : R) * u) • StrandSpace.dots R (k + l + t)) = 0 := by
  simp [zero_mul, zero_smul]

private theorem sum_inner_add (h : StrandSpace R) (k t : ℕ) (a b : R) :
    h.sum (fun l u => ((a + b) * u) • StrandSpace.dots R (k + l + t)) =
    h.sum (fun l u => (a * u) • StrandSpace.dots R (k + l + t)) +
    h.sum (fun l u => (b * u) • StrandSpace.dots R (k + l + t)) := by
  simp only [add_mul, add_smul, DFinsupp.sum, Finset.sum_add_distrib]

private theorem smul_dots_sum_single_index {R : Type u} [CommRing R] [DecidableEq R]
    (c : R) (m : ℕ) (g : ℕ → R → StrandSpace R) (hg : g m 0 = 0) :
    (c • StrandSpace.dots R m).sum g = g m c := by
  rw [StrandSpace.dots, ← DFinsupp.single_smul, smul_eq_mul, mul_one,
      DFinsupp.sum_single_index hg]

private theorem smul_dots_sum_lhs {R : Type u} [CommRing R] [DecidableEq R]
    (c : R) (m t : ℕ) (h : StrandSpace R) :
    (c • StrandSpace.dots R m).sum
      (fun k s => h.sum (fun l u => (s * u) • StrandSpace.dots R (k + l + t))) =
    h.sum (fun l u => (c * u) • StrandSpace.dots R (m + l + t)) := by
  rw [StrandSpace.dots, ← DFinsupp.single_smul, smul_eq_mul, mul_one,
      DFinsupp.sum_single_index (by simp [zero_mul, zero_smul])]

private theorem smul_dots_sum_rhs {R : Type u} [CommRing R] [DecidableEq R]
    (c : R) (m : ℕ) (r : R) (i t : ℕ) :
    (c • StrandSpace.dots R m).sum
      (fun k s => (r * s) • StrandSpace.dots R (i + k + t)) =
    (r * c) • StrandSpace.dots R (i + m + t) := by
  rw [StrandSpace.dots, ← DFinsupp.single_smul, smul_eq_mul, mul_one,
      DFinsupp.sum_single_index (by simp [mul_zero, zero_smul])]

end ConvolutionLemmas

instance : Category (KLRWCategory n R) where
  Hom X Y := StrandSpace R
  id X := StrandSpace.dots R 0
  comp {X Y Z} g h :=
    g.sum (fun i r => h.sum (fun j s =>
      (r * s) • StrandSpace.dots R (i + j + compShift X Y Z)))
  id_comp f := by
    rw [compShift_self_left]
    simp only [StrandSpace.dots]
    rw [DFinsupp.sum_single_index (by simp [zero_mul, zero_smul])]
    simp only [one_mul, zero_add, add_zero, ← DFinsupp.single_smul, smul_eq_mul, mul_one]
    exact DFinsupp.sum_single
  comp_id f := by
    rw [compShift_self_right]
    simp only [StrandSpace.dots]
    conv_lhs =>
      arg 2; ext i r
      rw [DFinsupp.sum_single_index (by simp [mul_zero, zero_smul])]
    simp [mul_one, add_zero, ← DFinsupp.single_smul, smul_eq_mul]
  assoc {W X Y Z} f g h := by
    -- Flatten LHS outer sum: pull f.sum out
    rw [DFinsupp.sum_sum_index (fun k => sum_inner_zero h k (compShift W Y Z))
          (fun k a b => sum_inner_add h k (compShift W Y Z) a b)]
    congr 1; funext i; funext r
    -- Flatten LHS inner sum: pull g.sum out
    rw [DFinsupp.sum_sum_index
          (fun k => sum_inner_zero h k (compShift W Y Z))
          (fun k a b => sum_inner_add h k (compShift W Y Z) a b)]
    -- Reduce (c • dots m).sum on LHS
    simp_rw [smul_dots_sum_lhs]
    -- LHS = g.sum(fun j s => h.sum(fun l u =>
    --   ((r*s)*u) • dots((i+j+compShift W X Y)+l+compShift W Y Z)))
    -- Flatten RHS: pull g.sum out
    symm
    rw [DFinsupp.sum_sum_index
          (fun k => by simp [mul_zero, zero_smul])
          (fun k a b => by simp [mul_add, add_smul])]
    congr 1; funext j; funext s
    -- Flatten RHS inner sum: pull h.sum out
    rw [DFinsupp.sum_sum_index
          (fun k => by simp [mul_zero, zero_smul])
          (fun k a b => by simp [mul_add, add_smul])]
    -- Reduce (c • dots m).sum on RHS
    simp_rw [smul_dots_sum_rhs]
    -- RHS = h.sum(fun l u =>
    --   (r*(s*u)) • dots(i+(j+l+compShift X Y Z)+compShift W X Z))
    symm
    -- Compare pointwise
    congr 1; funext l; funext u
    rw [mul_assoc]
    congr 1
    simpa [add_assoc, add_left_comm, add_comm] using
      congrArg (fun t => StrandSpace.dots R (i + j + l + t)) (compShift_assoc W X Y Z)

instance : Preadditive (KLRWCategory n R) where
  homGroup P Q := inferInstanceAs (AddCommGroup (StrandSpace R))
  add_comp := by
    intro P Q S f f' g
    letI : AddCommMonoid (StrandSpace R) := inferInstance
    exact DFinsupp.sum_add_index (fun k => sum_inner_zero g k (compShift P Q S))
      (fun k a b => sum_inner_add g k (compShift P Q S) a b)
  comp_add := by
    intro P Q S f g g'
    letI : AddCommMonoid (StrandSpace R) := inferInstance
    suffices h : (f : StrandSpace R).sum (fun i r =>
        (g + g' : StrandSpace R).sum
          (fun j s => (r * s) • StrandSpace.dots R (i + j + compShift P Q S))) =
      (f : StrandSpace R).sum (fun i r =>
        (g : StrandSpace R).sum
          (fun j s => (r * s) • StrandSpace.dots R (i + j + compShift P Q S))) +
      (f : StrandSpace R).sum (fun i r =>
        (g' : StrandSpace R).sum
          (fun j s => (r * s) • StrandSpace.dots R (i + j + compShift P Q S)))
      from h
    conv_lhs =>
      arg 2; ext i r
      rw [DFinsupp.sum_add_index (fun j => by simp [mul_zero, zero_smul])
        (fun j s₁ s₂ => by simp [mul_add, add_smul])]
    simp only [DFinsupp.sum, Finset.sum_add_distrib]

/-- `DFinsupp` analogue of `Finsupp.sum_smul_index`. -/
theorem sum_smul_index' {γ : Type*} [AddCommMonoid γ] (r : R) (f : StrandSpace R)
    (h : ℕ → R → γ) (h0 : ∀ i, h i 0 = 0) :
    (r • f).sum h = f.sum fun i c => h i (r * c) := by
  rw [show r • f = DFinsupp.mapRange (fun _ c => r * c) (fun _ => mul_zero r) f from by
      ext k; simp,
    DFinsupp.sum_mapRange_index h0]

theorem convolution_smul_left (r : R) (f g : StrandSpace R) (t : ℕ) :
    (r • f).sum (fun i c => g.sum fun j s => (c * s) • StrandSpace.dots R (i + j + t))
      = r • f.sum (fun i c => g.sum fun j s => (c * s) • StrandSpace.dots R (i + j + t)) := by
  rw [sum_smul_index' r f _ (fun i => by simp [zero_mul, zero_smul]), DFinsupp.smul_sum]
  congr 1; funext i c
  rw [DFinsupp.smul_sum]
  congr 1; funext j s
  rw [smul_smul, mul_assoc]

theorem convolution_smul_right (r : R) (f g : StrandSpace R) (t : ℕ) :
    f.sum (fun i c => (r • g).sum fun j s => (c * s) • StrandSpace.dots R (i + j + t))
      = r • f.sum (fun i c => g.sum fun j s => (c * s) • StrandSpace.dots R (i + j + t)) := by
  conv_lhs =>
    arg 2; ext i c
    rw [sum_smul_index' r g _ (fun j => by simp [mul_zero, zero_smul])]
  rw [DFinsupp.smul_sum]
  congr 1; funext i c
  rw [DFinsupp.smul_sum]
  congr 1; funext j s
  rw [smul_smul, mul_left_comm]

/-- The KLRW category is `R`-linear: Hom-spaces are `StrandSpace R` and the
convolution composition is `R`-bilinear. -/
instance : Linear R (KLRWCategory n R) where
  homModule _ _ := inferInstanceAs (Module R (StrandSpace R))
  smul_comp P Q S r f g := convolution_smul_left r f g (compShift P Q S)
  comp_smul P Q S f r g := convolution_smul_right r f g (compShift P Q S)

/-- The additive completion of an `R`-linear category is `R`-linear, with the
componentwise module structure on matrices of morphisms. (Stated here rather
than in `AdditiveCompletion` to avoid rebuilding its heavy dependents.) -/
instance {R : Type u} [CommRing R] {D : Type*} [Category D] [Preadditive D] [Linear R D] :
    Linear R (CMat_ D) where
  homModule M N := inferInstanceAs (Module R (∀ i j, M.X i ⟶ N.X j))
  smul_comp M N K r f g := by
    funext i k
    show ∑ j : N.ι, (r • f i j) ≫ g j k = r • ∑ j : N.ι, f i j ≫ g j k
    rw [Finset.smul_sum]
    exact Finset.sum_congr rfl fun j _ => Linear.smul_comp _ _ _ r (f i j) (g j k)
  comp_smul M N K f r g := by
    funext i k
    show ∑ j : N.ι, f i j ≫ (r • g j k) = r • ∑ j : N.ι, f i j ≫ g j k
    rw [Finset.smul_sum]
    exact Finset.sum_congr rfl fun j _ => Linear.comp_smul _ _ _ (f i j) r (g j k)

instance (R : Type*) [CommRing R] [DecidableEq R] [ToString R] (n : ℕ) (S T : KLRWCategory n R) :
  Texify (S ⟶ T) := inferInstanceAs (Texify (StrandSpace R))

/--
The KLRW Category lacks zero objects
-/
theorem KLRWCategory.not_isZero (R : Type*) [CommRing R] [DecidableEq R] [Nontrivial R] (n : ℕ)
    (A : KLRWCategory n R) : ¬ Limits.IsZero A := by
  intro hA
  have h_id_zero : (𝟙 A : A ⟶ A) = 0 := hA.eq_of_src (𝟙 A) 0
  have h_eval : (StrandSpace.dots R 0) 0 = (0 : StrandSpace R) 0 :=
    congrArg (fun f : StrandSpace R => f 0) h_id_zero
  rw [StrandSpace.dots] at h_eval
  rw [DFinsupp.single_eq_same] at h_eval
  change (1 : R) = 0 at h_eval
  exact one_ne_zero h_eval

instance (R : Type*) [CommRing R] [DecidableEq R] [Nontrivial R] (n : ℕ) :
    DecidablePred (Limits.IsZero : KLRWCategory n R → Prop) :=
  fun A ↦ Decidable.isFalse (A.not_isZero)

section KLRWAInfinity

open AInfinityCategoryTheory

/-- The graded Hom of the KLRW category: concentrated in degree `0`, where it
is `StrandSpace R`. -/
def klrwHom {R : Type u} [CommRing R] [DecidableEq R] {n : ℕ}
    (A B : KLRWCategory n R) : GradedRModule (β := ℤ) (R := R) :=
  fun d => if d = 0 then ModuleCat.of R (StrandSpace R) else ModuleCat.of R PUnit.{u + 1}

variable {R : Type u} [CommRing R] [DecidableEq R] {n : ℕ}

lemma klrwHom_subsingleton {A B : KLRWCategory n R} {d : ℤ} (hd : d ≠ 0) :
    Subsingleton (klrwHom (R := R) A B d) := by
  unfold klrwHom
  rw [if_neg hd]
  exact inferInstanceAs (Subsingleton PUnit)

/-- Away from degree `0`, all Hom-elements vanish. This is what forces the
degeneracy of the A∞-structure: `μₙ` lands in degree `2 − n`, so it must be
zero unless `n = 2`. -/
lemma klrwHom_eq_zero {A B : KLRWCategory n R} {d : ℤ} (hd : d ≠ 0)
    (x : klrwHom (R := R) A B d) : x = 0 :=
  @Subsingleton.elim _ (klrwHom_subsingleton hd) x 0

/-- Degree-level cast for `klrwHom`, as an `R`-linear map. -/
def klrwDegCast {A B : KLRWCategory n R} {d e : ℤ} (h : d = e) :
    klrwHom (R := R) A B d →ₗ[R] klrwHom (R := R) A B e := h ▸ LinearMap.id

/-- Composition of degree-`0` KLRW morphisms as an `R`-bilinear map (casting
away the degrees along `h₁`, `h₂`). Note `klrwHom A B 0` is definitionally
`A ⟶ B`, so this is convolution. -/
def klrwCompBilin {A B C : KLRWCategory n R} {d₁ d₂ : ℤ} (h₁ : d₁ = 0) (h₂ : d₂ = 0) :
    klrwHom (R := R) A B d₁ →ₗ[R] klrwHom (R := R) B C d₂ →ₗ[R] klrwHom (R := R) A C 0 :=
  LinearMap.mk₂ R
    (fun x y => show (A ⟶ C) from
      (show (A ⟶ B) from klrwDegCast (R := R) h₁ x) ≫
      (show (B ⟶ C) from klrwDegCast (R := R) h₂ y))
    (fun x x' y => by
      show (klrwDegCast (R := R) h₁ (x + x') ≫ _ : A ⟶ C) = _
      rw [map_add]
      exact Preadditive.add_comp _ _ _ _ _ _)
    (fun r x y => by
      show (klrwDegCast (R := R) h₁ (r • x) ≫ _ : A ⟶ C) = _
      rw [map_smul]
      exact Linear.smul_comp _ _ _ r _ _)
    (fun x y y' => by
      show (_ ≫ klrwDegCast (R := R) h₂ (y + y') : A ⟶ C) = _
      rw [map_add]
      exact Preadditive.comp_add _ _ _ _ _ _)
    (fun r x y => by
      show (_ ≫ klrwDegCast (R := R) h₂ (r • y) : A ⟶ C) = _
      rw [map_smul]
      exact Linear.comp_smul _ _ _ _ r _)

/-- KLRW as a (degenerate) A∞-pre-category over `R`: Hom concentrated in degree
`0`, `μ₁ = 0`, `μ₂` = the convolution composition, `μₙ = 0` for `n ≥ 3`. The
grading itself forces the degeneracy — `μₙ` has target degree `2 − n`, which is
the zero module unless `n = 2` (`klrwHom_eq_zero`). -/
def klrwAInfinityPreCategory :
    AInfinityPreCategory (β := ℤ) R (KLRWCategory n R) where
  Hom := klrwHom (R := R)
  m {k} obj deg := by
    obtain ⟨k, hk⟩ := k
    match k with
    | 0 => exact absurd hk (Nat.lt_irrefl 0)
    | 1 =>
      -- μ₁ = 0 (it lands in degree `deg 0 + 1 ≠ deg 0`, but we simply take 0)
      exact 0
    | 2 =>
      -- μ₂ = convolution on the degree-(0, 0) chains, 0 elsewhere (where some
      -- slot is the zero module anyway).
      exact
        if h : deg ⟨0, hk⟩ = 0 ∧ deg ⟨1, Nat.lt_succ_self 1⟩ = 0 then
          (klrwDegCast (R := R) (show (0 : ℤ) = operationTargetDeg deg from by
              have h0 : ∀ i, deg i = 0 := fun i => by fin_cases i; exacts [h.1, h.2]
              simp [operationTargetDeg, shift_ofInt_int, Fin.sum_univ_two,
                h0])).compMultilinearMap
            { toFun := fun v =>
                klrwCompBilin (R := R) h.1 h.2 (v ⟨0, hk⟩) (v ⟨1, Nat.lt_succ_self 1⟩)
              map_update_add' := fun v i x y => by
                fin_cases i
                · simpa using
                    LinearMap.map_add₂ (klrwCompBilin (R := R) h.1 h.2) x y
                      (v ⟨1, Nat.lt_succ_self 1⟩)
                · simpa using
                    map_add (klrwCompBilin (R := R) h.1 h.2 (v ⟨0, hk⟩)) x y
              map_update_smul' := fun v i r x => by
                fin_cases i
                · simpa using
                    LinearMap.map_smul₂ (klrwCompBilin (R := R) h.1 h.2) r x
                      (v ⟨1, Nat.lt_succ_self 1⟩)
                · simpa using
                    map_smul (klrwCompBilin (R := R) h.1 h.2 (v ⟨0, hk⟩)) r x }
        else 0
    | _ + 3 =>
      -- μₙ = 0 for n ≥ 3
      exact 0

/-- `μ₁` of the KLRW A∞-structure is the zero map (application form). -/
lemma klrwM_one_eq_zero (h : 0 < 1) (obj : Fin 2 → KLRWCategory n R) (deg : Fin 1 → ℤ) :
    klrwAInfinityPreCategory.m (R := R) (n := ⟨1, h⟩) obj deg = 0 := rfl

/-- `μₖ = 0` for `k ≥ 3` (application form). -/
lemma klrwM_ge_three_eq_zero (k : ℕ) (h : 0 < k + 3)
    (obj : Fin (k + 3 + 1) → KLRWCategory n R) (deg : Fin (k + 3) → ℤ) :
    klrwAInfinityPreCategory.m (R := R) (n := ⟨k + 3, h⟩) obj deg = 0 := rfl

end KLRWAInfinity

/-! ### KLRW is a (degenerate) A∞-category

The Stasheff identities for `klrwAInfinityPreCategory`. Since `μ₁ = 0` and
`μₖ = 0` for `k ≥ 3`, every Stasheff term vanishes — through a zero inner or
outer operation, or a `μ₂` whose degree vector is not `(0, 0)` — except the two
`μ₂(μ₂ ⊗ 1)` / `μ₂(1 ⊗ μ₂)` insertion terms in arity 3 at all-zero degrees,
which cancel by associativity of convolution. -/

section KLRWStasheff

open AInfinityCategoryTheory

variable {R : Type*} [CommRing R] [DecidableEq R] {n : ℕ}

private lemma cast_zero_eq {S : Type*} [CommRing S] {A B : ModuleCat S} (h : A = B) :
    h ▸ (0 : A) = (0 : B) := by cases h; rfl

private lemma cast_zero_iff {S : Type*} [CommRing S] {A B : ModuleCat S} (h : A = B) {a : A} :
    h ▸ a = (0 : B) ↔ a = (0 : A) := by cases h; simp

private lemma cast_zero_of_modcat_eq {S : Type*} [CommRing S] {A B : ModuleCat S}
    (h : A = B) {T_mid : Type*} (h₁ : ↑A = T_mid) (h₂ : ↑B = T_mid) :
    Eq.mpr h₂ (Eq.mp h₁ (0 : ↑A)) = (0 : ↑B) := by
  subst h; subst h₁; cases h₂; rfl

/-- For `j ≥ 3`, the KLRW A∞ operation is the zero multilinear map
(`3 ≤ j` form of `klrwM_ge_three_eq_zero`). -/
lemma klrwM_zero_of_ge_three {j : ℕ} (hj : 3 ≤ j)
    {obj : Fin (j + 1) → KLRWCategory n R} {deg : Fin j → ℤ} :
    klrwAInfinityPreCategory.m (R := R) (n := ⟨j, by omega⟩) obj deg = 0 := by
  obtain ⟨k, rfl⟩ : ∃ k, j = k + 3 := ⟨j - 3, by omega⟩
  rfl

-- μ₂ is the zero map unless both slot degrees are 0 (the dite in its definition).
private lemma klrwM_two_eq_zero {obj : Fin 3 → KLRWCategory n R} {deg : Fin 2 → ℤ}
    (hk : 0 < 2) (h : ¬(deg ⟨0, hk⟩ = 0 ∧ deg ⟨1, Nat.lt_succ_self 1⟩ = 0)) :
    klrwAInfinityPreCategory.m (R := R) (n := ⟨2, hk⟩) obj deg = 0 := dif_neg h

-- If the outer multilinear map is zero, the entire Stasheff term is zero.
private lemma klrwTerm_outer_zero
    {k : ℕ+}
    {obj : Fin (k.val + 1) → KLRWCategory n R} {deg : Fin k.val → ℤ}
    {x : ∀ i : Fin k.val,
      composableHomType (β := ℤ) (R := R) (klrwHom (R := R) (n := n)) obj deg i}
    {r s : ℕ} {hs : 1 ≤ s} {hr : r + s ≤ k.val}
    (hm : klrwAInfinityPreCategory.m (R := R) (n := ⟨k.val + 1 - s, by omega⟩)
        (stasheffObjOut obj r s hr) (stasheffDegOut deg r s hr) = 0) :
    indexedStasheffTerm (β := ℤ) (R := R) (n := k) (klrwHom (R := R) (n := n))
        (fun {m} => klrwAInfinityPreCategory.m) obj deg x r s hs hr = 0 := by
  simp only [indexedStasheffTerm, hm, MultilinearMap.zero_apply]
  exact cast_zero_eq _

-- If the inner multilinear map is zero, the Stasheff term is zero
-- (slot r of the outer input vector becomes cast(0) = 0).
set_option maxHeartbeats 800000 in
private lemma klrwTerm_inner_zero
    {k : ℕ+}
    {obj : Fin (k.val + 1) → KLRWCategory n R} {deg : Fin k.val → ℤ}
    {x : ∀ i : Fin k.val,
      composableHomType (β := ℤ) (R := R) (klrwHom (R := R) (n := n)) obj deg i}
    {r s : ℕ} {hs : 1 ≤ s} {hr : r + s ≤ k.val}
    (hm : klrwAInfinityPreCategory.m (R := R) (n := ⟨s, by omega⟩)
        (stasheffObjIn obj r s hr) (stasheffDegIn deg r s hr) = 0) :
    indexedStasheffTerm (β := ℤ) (R := R) (n := k) (klrwHom (R := R) (n := n))
        (fun {m} => klrwAInfinityPreCategory.m) obj deg x r s hs hr = 0 := by
  apply cast_zero_iff _ |>.mpr
  convert MultilinearMap.map_coord_zero _ _ _
  exact ⟨r, Nat.lt_sub_of_add_lt (by omega)⟩
  convert cast_zero_of_modcat_eq _ _ _
  rotate_left
  exact operationTargetType (klrwHom (R := R) (n := n))
    (stasheffObjIn obj r s hr) (stasheffDegIn deg r s hr)
  all_goals norm_num [operationTargetType, composableHomType]
  rotate_left
  exact ↑(klrwHom (R := R) (n := n) (stasheffObjIn obj r s hr 0)
    (stasheffObjIn obj r s hr (Fin.last s)) (operationTargetDeg (stasheffDegIn deg r s hr)))
  · rfl
  · unfold stasheffObjOut stasheffObjIn stasheffDegOut operationTargetDeg
    simp +decide [Nat.mod_eq_of_lt]
    rfl
  · exact hm.symm ▸ rfl
  · simp +decide [stasheffObjIn, stasheffObjOut, stasheffDegIn, stasheffDegOut,
      operationTargetDeg]
    congr! 2

private lemma klrw_stasheff_one
    (obj : Fin ((1 : ℕ+).val + 1) → KLRWCategory n R)
    (deg : Fin (1 : ℕ+).val → ℤ)
    (x : ∀ i : Fin (1 : ℕ+).val,
      composableHomType (β := ℤ) (R := R) (klrwHom (R := R) (n := n)) obj deg i) :
    indexedStasheffSum (β := ℤ) (R := R) (n := (1 : ℕ+)) (klrwHom (R := R) (n := n))
        (fun {m} => klrwAInfinityPreCategory.m) obj deg x = 0 := by
  simp only [indexedStasheffSum]
  apply Finset.sum_eq_zero
  intro ⟨r, hr_mem⟩ _
  apply Finset.sum_eq_zero
  intro ⟨s, hs_mem⟩ _
  have hv := validStasheffIndices_of_mem_ranges (n := 1) hr_mem hs_mem
  suffices h : indexedStasheffTerm (β := ℤ) (n := (1 : ℕ+)) (klrwHom (R := R) (n := n))
      (fun {m} => klrwAInfinityPreCategory.m) obj deg x r s hv.1 hv.2 = 0 by
    rw [h, smul_zero]
  have hs1 : s = 1 := by have := hv.1; have := hv.2; omega
  subst hs1
  -- outer arity 1 + 1 - 1 = 1: the outer map is μ₁ = 0
  exact klrwTerm_outer_zero (klrwM_one_eq_zero _ _ _)

private lemma klrw_stasheff_two
    (obj : Fin ((2 : ℕ+).val + 1) → KLRWCategory n R)
    (deg : Fin (2 : ℕ+).val → ℤ)
    (x : ∀ i : Fin (2 : ℕ+).val,
      composableHomType (β := ℤ) (R := R) (klrwHom (R := R) (n := n)) obj deg i) :
    indexedStasheffSum (β := ℤ) (R := R) (n := (2 : ℕ+)) (klrwHom (R := R) (n := n))
        (fun {m} => klrwAInfinityPreCategory.m) obj deg x = 0 := by
  simp only [indexedStasheffSum]
  apply Finset.sum_eq_zero
  intro ⟨r, hr_mem⟩ _
  apply Finset.sum_eq_zero
  intro ⟨s, hs_mem⟩ _
  have hv := validStasheffIndices_of_mem_ranges (n := 2) hr_mem hs_mem
  suffices h : indexedStasheffTerm (β := ℤ) (n := (2 : ℕ+)) (klrwHom (R := R) (n := n))
      (fun {m} => klrwAInfinityPreCategory.m) obj deg x r s hv.1 hv.2 = 0 by
    rw [h, smul_zero]
  by_cases hs1 : s = 1
  · subst hs1
    -- inner arity 1: the inner map is μ₁ = 0
    exact klrwTerm_inner_zero (klrwM_one_eq_zero _ _ _)
  · have hs2 : s = 2 := by have := hv.1; have := hv.2; omega
    subst hs2
    -- outer arity 2 + 1 - 2 = 1: the outer map is μ₁ = 0
    exact klrwTerm_outer_zero (klrwM_one_eq_zero _ _ _)

private lemma klrw_stasheff_ge_four (j : ℕ)
    (obj : Fin (j + 5) → KLRWCategory n R)
    (deg : Fin (j + 4) → ℤ)
    (x : ∀ i : Fin (j + 4),
      composableHomType (β := ℤ) (R := R) (klrwHom (R := R) (n := n)) obj deg i) :
    indexedStasheffSum (β := ℤ) (R := R) (n := ⟨j + 4, by omega⟩) (klrwHom (R := R) (n := n))
        (fun {m} => klrwAInfinityPreCategory.m) obj deg x = 0 := by
  simp only [indexedStasheffSum]
  apply Finset.sum_eq_zero
  intro ⟨r, hr_mem⟩ _
  apply Finset.sum_eq_zero
  intro ⟨s, hs_mem⟩ _
  have hv := validStasheffIndices_of_mem_ranges (n := j + 4) hr_mem hs_mem
  suffices h : indexedStasheffTerm (β := ℤ) (n := ⟨j + 4, by omega⟩) (klrwHom (R := R) (n := n))
      (fun {m} => klrwAInfinityPreCategory.m) obj deg x r s hv.1 hv.2 = 0 by
    rw [h, smul_zero]
  by_cases hs3 : s ≤ 2
  · -- outer arity = (j+4)+1-s ≥ 3, so the outer map is zero
    apply klrwTerm_outer_zero
    apply klrwM_zero_of_ge_three
    change 3 ≤ j + 4 + 1 - s
    omega
  · -- inner arity = s ≥ 3, so the inner map is zero
    push Not at hs3
    exact klrwTerm_inner_zero (klrwM_zero_of_ge_three (by omega))

-- The associativity cancellation: at all-zero degrees the two surviving arity-3
-- terms agree, `μ₂(μ₂(x₀, x₁), x₂) = μ₂(x₀, μ₂(x₁, x₂))`. With the degree
-- function literally `fun _ => 0`, every cast in both terms has closed,
-- kernel-evaluable degree endpoints, so the entire cast tower collapses
-- definitionally and the terms reduce to `(x₀ ≫ x₁) ≫ x₂` and `x₀ ≫ (x₁ ≫ x₂)`:
-- the identity IS `Category.assoc` (whose content is `compShift_assoc`).
set_option maxHeartbeats 4000000 in
private lemma klrw_stasheff_three_assoc
    (obj : Fin ((3 : ℕ+).val + 1) → KLRWCategory n R)
    (x : ∀ i : Fin (3 : ℕ+).val,
      composableHomType (β := ℤ) (R := R) (klrwHom (R := R) (n := n)) obj
        (fun _ => (0 : ℤ)) i) :
    ∀ (hs : 1 ≤ 2) (hr02 : 0 + 2 ≤ 3),
    indexedStasheffTerm (β := ℤ) (R := R) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
        (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 0 2 hs hr02 =
    indexedStasheffTerm (β := ℤ) (R := R) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
        (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 1 2
        (by norm_num) (by norm_num) :=
  fun _ _ =>
    Category.assoc
      (show obj ⟨0, by norm_num⟩ ⟶ obj ⟨1, by norm_num⟩ from x ⟨0, by norm_num⟩)
      (show obj ⟨1, by norm_num⟩ ⟶ obj ⟨2, by norm_num⟩ from x ⟨1, by norm_num⟩)
      (show obj ⟨2, by norm_num⟩ ⟶ obj ⟨3, by norm_num⟩ from x ⟨2, by norm_num⟩)

set_option maxHeartbeats 4000000 in
private lemma klrw_stasheff_three
    (obj : Fin ((3 : ℕ+).val + 1) → KLRWCategory n R)
    (deg : Fin (3 : ℕ+).val → ℤ)
    (x : ∀ i : Fin (3 : ℕ+).val,
      composableHomType (β := ℤ) (R := R) (klrwHom (R := R) (n := n)) obj deg i) :
    indexedStasheffSum (β := ℤ) (R := R) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
        (fun {m} => klrwAInfinityPreCategory.m) obj deg x = 0 := by
  by_cases hd : deg ⟨0, by norm_num⟩ = 0 ∧ deg ⟨1, by norm_num⟩ = 0 ∧
      deg ⟨2, by norm_num⟩ = 0
  · -- all degrees 0: only the two s = 2 insertion terms survive, with opposite
    -- signs; they cancel by associativity of convolution.
    obtain ⟨h0, h1, h2⟩ := hd
    have hdeg : deg = fun _ => (0 : ℤ) := funext fun i => by
      fin_cases i
      exacts [h0, h1, h2]
    subst hdeg
    simp only [indexedStasheffSum, PNat.val_ofNat]
    rw [show (Finset.range (3 + 1) : Finset ℕ).attach =
        ({⟨0, by decide⟩, ⟨1, by decide⟩, ⟨2, by decide⟩, ⟨3, by decide⟩} :
          Finset { a // a ∈ Finset.range (3 + 1) }) from by decide]
    rw [Finset.sum_insert (by decide), Finset.sum_insert (by decide),
      Finset.sum_insert (by decide), Finset.sum_singleton]
    rw [show (Finset.Ico 1 (3 - (0 : ℕ) + 1) : Finset ℕ).attach =
        ({⟨1, by decide⟩, ⟨2, by decide⟩, ⟨3, by decide⟩} :
          Finset { a // a ∈ (Finset.Ico 1 (3 - (0 : ℕ) + 1) : Finset ℕ) }) from by decide]
    rw [show (Finset.Ico 1 (3 - (1 : ℕ) + 1) : Finset ℕ).attach =
        ({⟨1, by decide⟩, ⟨2, by decide⟩} :
          Finset { a // a ∈ (Finset.Ico 1 (3 - (1 : ℕ) + 1) : Finset ℕ) }) from by decide]
    rw [show (Finset.Ico 1 (3 - (2 : ℕ) + 1) : Finset ℕ).attach =
        ({⟨1, by decide⟩} :
          Finset { a // a ∈ (Finset.Ico 1 (3 - (2 : ℕ) + 1) : Finset ℕ) }) from by decide]
    rw [show (Finset.Ico 1 (3 - (3 : ℕ) + 1) : Finset ℕ).attach =
        (∅ : Finset { a // a ∈ (Finset.Ico 1 (3 - (3 : ℕ) + 1) : Finset ℕ) }) from by decide]
    rw [Finset.sum_insert (by decide), Finset.sum_insert (by decide),
      Finset.sum_singleton, Finset.sum_insert (by decide), Finset.sum_singleton,
      Finset.sum_singleton, Finset.sum_empty]
    -- kill the four zero terms: s = 1 (inner μ₁ = 0) and s = 3 (outer arity 1)
    have e01 : ∀ (hs : 1 ≤ 1) (hr : 0 + 1 ≤ 3),
        indexedStasheffTerm (β := ℤ) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
          (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 0 1 hs hr = 0 :=
      fun _ _ => klrwTerm_inner_zero (klrwM_one_eq_zero _ _ _)
    have e11 : ∀ (hs : 1 ≤ 1) (hr : 1 + 1 ≤ 3),
        indexedStasheffTerm (β := ℤ) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
          (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 1 1 hs hr = 0 :=
      fun _ _ => klrwTerm_inner_zero (klrwM_one_eq_zero _ _ _)
    have e21 : ∀ (hs : 1 ≤ 1) (hr : 2 + 1 ≤ 3),
        indexedStasheffTerm (β := ℤ) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
          (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 2 1 hs hr = 0 :=
      fun _ _ => klrwTerm_inner_zero (klrwM_one_eq_zero _ _ _)
    have e03 : ∀ (hs : 1 ≤ 3) (hr : 0 + 3 ≤ 3),
        indexedStasheffTerm (β := ℤ) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
          (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 0 3 hs hr = 0 :=
      fun _ _ => klrwTerm_outer_zero (klrwM_one_eq_zero _ _ _)
    show stasheffSign (fun _ => (0 : ℤ)) 0 1 (by decide) •
        indexedStasheffTerm (β := ℤ) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
          (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 0 1 (by decide) (by decide) +
      ((-1 : ℤ) •
        indexedStasheffTerm (β := ℤ) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
          (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 0 2 (by decide) (by decide) +
        stasheffSign (fun _ => (0 : ℤ)) 0 3 (by decide) •
        indexedStasheffTerm (β := ℤ) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
          (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 0 3 (by decide) (by decide)) +
      (stasheffSign (fun _ => (0 : ℤ)) 1 1 (by decide) •
        indexedStasheffTerm (β := ℤ) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
          (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 1 1 (by decide) (by decide) +
        (1 : ℤ) •
        indexedStasheffTerm (β := ℤ) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
          (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 1 2 (by decide) (by decide) +
        (stasheffSign (fun _ => (0 : ℤ)) 2 1 (by decide) •
        indexedStasheffTerm (β := ℤ) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
          (fun {m} => klrwAInfinityPreCategory.m) obj (fun _ => (0 : ℤ)) x 2 1 (by decide) (by decide) +
          0)) = 0
    rw [e01, e11, e21, e03,
      klrw_stasheff_three_assoc obj x]
    -- a canonical-instance key lemma closes the arithmetic
    have key : ∀ {S : Type u_1} [CommRing S] {M : ModuleCat S} (T : M) (a b c d : ℤ),
        a • (0 : M) + ((-1 : ℤ) • T + b • (0 : M)) +
          (c • (0 : M) + (1 : ℤ) • T + (d • (0 : M) + (0 : M))) = 0 := by
      intro S _ M T a b c d
      simp
    apply key
  · -- some degree ≠ 0: every term vanishes
    simp only [indexedStasheffSum]
    apply Finset.sum_eq_zero
    intro ⟨r, hr_mem⟩ _
    apply Finset.sum_eq_zero
    intro ⟨s, hs_mem⟩ _
    have hv := validStasheffIndices_of_mem_ranges (n := 3) hr_mem hs_mem
    suffices h : indexedStasheffTerm (β := ℤ) (n := (3 : ℕ+)) (klrwHom (R := R) (n := n))
        (fun {m} => klrwAInfinityPreCategory.m) obj deg x r s hv.1 hv.2 = 0 by
      rw [h, smul_zero]
    by_cases hs1 : s = 1
    · subst hs1
      exact klrwTerm_inner_zero (klrwM_one_eq_zero _ _ _)
    by_cases hs3 : s = 3
    · subst hs3
      -- outer arity 3 + 1 - 3 = 1
      exact klrwTerm_outer_zero (klrwM_one_eq_zero _ _ _)
    have hs2 : s = 2 := by have := hv.1; have := hv.2; omega
    subst hs2
    have hr1 : r = 0 ∨ r = 1 := by have := hv.2; omega
    rcases hr1 with rfl | rfl
    · -- term (0,2): inner slots (deg 0, deg 1), outer slots (—, deg 2)
      by_cases h01 : deg ⟨0, by norm_num⟩ = 0 ∧ deg ⟨1, by norm_num⟩ = 0
      · have h2 : ¬ deg ⟨2, by norm_num⟩ = 0 := fun h2 => hd ⟨h01.1, h01.2, h2⟩
        exact klrwTerm_outer_zero (klrwM_two_eq_zero _ fun hcon => h2 hcon.2)
      · exact klrwTerm_inner_zero (klrwM_two_eq_zero _ fun hcon => h01 ⟨hcon.1, hcon.2⟩)
    · -- term (1,2): inner slots (deg 1, deg 2), outer slots (deg 0, —)
      by_cases h12 : deg ⟨1, by norm_num⟩ = 0 ∧ deg ⟨2, by norm_num⟩ = 0
      · have h0 : ¬ deg ⟨0, by norm_num⟩ = 0 := fun h0 => hd ⟨h0, h12.1, h12.2⟩
        exact klrwTerm_outer_zero (klrwM_two_eq_zero _ fun hcon => h0 hcon.1)
      · exact klrwTerm_inner_zero (klrwM_two_eq_zero _ fun hcon => h12 ⟨hcon.1, hcon.2⟩)

/-- KLRW as an A∞-category: the Stasheff identities hold for the degenerate
structure `klrwAInfinityPreCategory`. -/
def klrwAInfinityCategory : AInfinityCategory (β := ℤ) R (KLRWCategory n R) where
  toAInfinityPreCategory := klrwAInfinityPreCategory
  stasheff := by
    intro k obj deg x
    obtain ⟨k, hk⟩ := k
    match k with
    | 0 => exact absurd hk (Nat.lt_irrefl 0)
    | 1 => exact klrw_stasheff_one obj deg x
    | 2 => exact klrw_stasheff_two obj deg x
    | k + 3 =>
      match k with
      | 0 => exact klrw_stasheff_three obj deg x
      | j + 1 => exact klrw_stasheff_ge_four j obj deg x

end KLRWStasheff

abbrev AddKLRWCategory (n : ℕ) (R : Type u) [CommRing R] [DecidableEq R] : Type _ :=
  CMat_ (KLRWCategory n R)

abbrev KLRWComplexCategory (n : ℕ) (R : Type u) [CommRing R] [DecidableEq R] : Type _ :=
  BoundedCochainComplex (AddKLRWCategory n R)

/-- `K^•(Add KLRW)` is an A∞-category. The proof is the generic dg-category
instance in `BoundedCochainComplex.lean` (`bccAInfinityPreCategory` and the
fully-proven Stasheff identities), specialized to `V := CMat_ (KLRWCategory n R)`
via the `Linear R` instances above. -/
def klrwComplexAInfinityCategory {R : Type u} [CommRing R] [DecidableEq R] {n : ℕ}
    [DecidablePred (Limits.IsZero (C := CMat_ (KLRWCategory n R)))] :
    AInfinityCategoryTheory.AInfinityCategory (β := ℤ) R (KLRWComplexCategory n R) :=
  BoundedCochainComplex.instAInfinityCategoryInt

end AInfinityTheory
